GET http://localhost:4000/admin


###

GET http://localhost:4000/admin/15


###

POST http://localhost:4000/admin
Content-Type: application/json

{
    "id": "1",
    "name" : "johndoe",
    "type" : "idk"
}